# For more information on configuration, see: http://nginx.org/en/docs/

events {
    worker_connections 1024;
}

pid /tmp/nginx.pid;

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 8080;
        server_name _;

        # health check
        location /healthz {
            default_type text/html;
            return 200 "<!DOCTYPE html><p>Web Tier Health Check</p>\n";
        }

        # react app and front end files
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri /index.html;
        }

        # proxy for the backend service (Docker Compose network alias)
        location /api/ {
            proxy_pass http://backend:4000/;
        }
    }
}
